apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  ttlSecondsAfterFinished: 30
  suspend: false
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "echo Hello from knowhere"]
      restartPolicy: Never  


      
    