apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-demo-rs
  labels:
    app: nginx
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: production
    matchExpressions:
      - {key: app, operator: Exists}
      - {key: type, operator: DoesNotExist}
  template:
    metadata:
      name: nginx-demo
      labels:
        app: nginx
        environment: production  
        release: v1.2
    spec:
      containers:
      - name: write-container
        image: alpine
        command: ["/bin/sh"]  
        args: ["-c", "while true;do date >> /var/log/index.html; sleep 10;done"]
        volumeMounts:
          - name: shared-data
            mountPath: /var/log
      - name: serving-container
        image: nginx:1.25.4
        ports:
          - containerPort: 80
        volumeMounts:
          - name: shared-data
            mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-data  
          emptyDir: {}              